// cpp-httplib + cpp-embedlib integration helper.
// SPDX-License-Identifier: MIT
//
// Usage:
//   #include "WebAssets.h"  // generated by cpp_embedlib_add()
//
//   httplib::Server svr;
//   httplib::mount(svr, Web::FS);             // serve at "/"
//   httplib::mount(svr, Web::FS, "/static");  // serve at "/static/"
//   svr.listen("0.0.0.0", 8080);
#pragma once

#include <cpp-embedlib/cpp-embedlib.h>
#include <httplib.h>
#include <string>

namespace httplib {

inline void mount(Server &svr, const cpp_embedlib::EmbeddedFS &fs,
                  const std::string &url_prefix = "/") {
  auto prefix = url_prefix;

  // Ensure prefix ends with /
  if (!prefix.empty() && prefix.back() != '/') { prefix += '/'; }

  svr.Get(prefix + "(.*)", [&fs](const Request &req, Response &res) {
    auto path = req.matches[1].str();
    if (path.empty()) path = "index.html";

    auto it = fs.find(path);
    if (it == fs.end() || (*it).is_dir()) {
      res.status = 404;
      return;
    }

    auto entry = *it;
    auto data = entry.bytes().value();
    res.set_content(reinterpret_cast<const char *>(data.data()), data.size(),
                    std::string(entry.mime_type()));
  });
}

} // namespace httplib
