# cpp-embedlib: Build-time code generation script.
# Invoked via: cmake -P cpp-embedlib-generate.cmake
#   -DINPUT_FILE=<path>   Input binary file
#   -DOUTPUT_FILE=<path>  Output .cpp file
#   -DSYM_NAME=<name>     C++ symbol name (e.g., _data_index_html)
#   -DNAMESPACE=<ns>      C++ namespace
#
# SPDX-License-Identifier: MIT

# Validate required arguments
foreach(_arg INPUT_FILE OUTPUT_FILE SYM_NAME NAMESPACE)
    if(NOT DEFINED ${_arg})
        message(FATAL_ERROR "cpp-embedlib-generate: missing required argument ${_arg}")
    endif()
endforeach()

# Read file as hex (always binary mode)
file(READ "${INPUT_FILE}" _hex_content HEX)
string(LENGTH "${_hex_content}" _hex_len)

# Calculate byte count (2 hex chars per byte)
math(EXPR _byte_count "${_hex_len} / 2")

if(_byte_count EQUAL 0)
    # Empty file: use {0} sentinel with size = 0
    set(_array_body "    0x00")
    set(_size_expr "0")
else()
    # Convert pairs of hex chars to 0xXX, format
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _formatted "${_hex_content}")
    # Insert newline + indent every 16 bytes (80 chars = 5 chars * 16)
    string(REGEX REPLACE "(.{80})" "\\1\n    " _formatted "${_formatted}")
    # Remove trailing comma
    string(REGEX REPLACE ",$" "" _formatted "${_formatted}")
    set(_array_body "    ${_formatted}")
    set(_size_expr "sizeof(${SYM_NAME})")
endif()

# Generate C++ source
file(WRITE "${OUTPUT_FILE}"
"// Auto-generated by cpp-embedlib. DO NOT EDIT.
#include <cstdint>

namespace ${NAMESPACE} { namespace _impl {

// extern: const at namespace scope has internal linkage by default in C++
extern const unsigned char ${SYM_NAME}[] = {
${_array_body}
};

extern const std::uint32_t ${SYM_NAME}_size = ${_size_expr};

}} // namespace ${NAMESPACE}::_impl
")
